# Generated by Django 5.1.3 on 2024-11-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_borrowhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
